//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class movies
    {
        public int movieid { get; set; }
        [Required]
        [Display(Name = "Movie Title")]
        public string movietitle { get; set; }
        [Display(Name ="Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public System.DateTime releasedate { get; set; }
        [Required]
        [Display(Name = "Genre")]
        public string genre { get; set; }
        [Display(Name = "Image")]
        public string img { get; set; }
        [Display(Name = "Trailer")]
        public string video { get; set; }
        [Required]
        public Nullable<Double> price { get; set; }
    }
}
